<a href="https://colab.research.google.com/github/BRIJNANDA1979/Segmenting-Kelp-Forests-/blob/main/CNN_for_KELP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Next Step is CNN training with Train 5635 1 band  and rejected 469 7Band data.
469*7 = 3293  rejected  Label 0
5635 Trained   Label 1

Total in training:  8928

In [6]:
import pandas as pd
import os

In [7]:
train_kelp_path = '/content/drive/MyDrive/train_kelp'

In [8]:
train_kelp_files_list = os.listdir(train_kelp_path)

In [9]:
test_satellite_path = '/content/drive/MyDrive/test_satellite'

In [10]:
test_satellite_files_list = os.listdir(test_satellite_path)

In [11]:
Predicted = os.listdir('/content/drive/MyDrive/Predicted_all_bands_files')

In [12]:
len(Predicted)

6699

Rejected files  =   Test_satelleite - Predicted

469 7-Band files

In [13]:
for file in Predicted:
  s = file.split('_')
  ss = s[0] + '_satellite.tif'
  #print(ss)
  if ss in test_satellite_files_list:
    test_satellite_files_list.remove(ss)

In [14]:
len(test_satellite_files_list)

469

In [15]:
rejected_files_list = test_satellite_files_list

In [16]:
rejected_files_list[0:2]

['HP504630_satellite.tif', 'HR677407_satellite.tif']

In [17]:
rejected_list_with_7_bands = []
for i in rejected_files_list:
  for j in range(1,8):
    rejected_list_with_7_bands.append(i.split('.')[0]  + str(j) + '.tif')


In [18]:
rejected_list_with_7_bands[0:8]

['HP504630_satellite1.tif',
 'HP504630_satellite2.tif',
 'HP504630_satellite3.tif',
 'HP504630_satellite4.tif',
 'HP504630_satellite5.tif',
 'HP504630_satellite6.tif',
 'HP504630_satellite7.tif',
 'HR677407_satellite1.tif']

In [19]:
len(train_kelp_files_list)

5635

In [20]:
train_kelp_files_list[0:2]

['VN257517_kelp.tif', 'VN609253_kelp.tif']

In [21]:
X_list = train_kelp_files_list + rejected_list_with_7_bands

In [22]:
len(X_list)

8918

In [23]:
df = pd.DataFrame(X_list, columns=['file_name'])

In [24]:
df['file_name'][5633:5635]

5633    CW256294_kelp.tif
5634    CW399607_kelp.tif
Name: file_name, dtype: object

In [25]:
df['file_name'][5635:5640]

5635    HP504630_satellite1.tif
5636    HP504630_satellite2.tif
5637    HP504630_satellite3.tif
5638    HP504630_satellite4.tif
5639    HP504630_satellite5.tif
Name: file_name, dtype: object

In [26]:
label =[]
for i in range(0,5635):
  label.append(1)
for i in range(5635,8918):
  label.append(0)

In [27]:
df['label'] = label

In [28]:
df.head()

file_name  label
0  VN257517_kelp.tif      1
1  VN609253_kelp.tif      1
2  VN630519_kelp.tif      1
3  VN633188_kelp.tif      1
4  VN645015_kelp.tif      1

In [29]:
df.tail()

file_name  label
8913  HL852722_satellite3.tif      0
8914  HL852722_satellite4.tif      0
8915  HL852722_satellite5.tif      0
8916  HL852722_satellite6.tif      0
8917  HL852722_satellite7.tif      0

In [30]:
df['label'].value_counts()

1    5635
0    3283
Name: label, dtype: int64

In [31]:
pip install rasterio

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.6/20.6 MB 43.1 MB/s eta 0:00:00


In [37]:
s = 'GV801444_satellite2.tif'
s = s.split('_')


In [52]:
int(s[1][-5])

2

In [32]:
import rasterio

In [53]:
XX = []
YY = []
for i in df['file_name']:
  print(i)
  if i in train_kelp_files_list:
    with rasterio.open('/content/drive/MyDrive/train_kelp/' + i) as src:
      print(src.shape)
      print(src.meta)
      print(src.read(1))
      data_array = src.read(1)    ##### _kelp is 1 Band only
      XX.append(data_array)
      YY.append(1)
  else:
    s = i.split('_')
    ss = s[0] + '_satellite.tif'
    band = int(s[1][-5])
    with rasterio.open('/content/drive/MyDrive/test_satellite/' +ss) as src:
        data_array = src.read(band)     #### _satellite is 7 bands 1-7
        XX.append(data_array)
        YY.append(0)


VN257517_kelp.tif
(350, 350)
{'driver': 'GTiff', 'dtype': 'int8', 'nodata': None, 'width': 350, 'height': 350, 'count': 1, 'crs': None, 'transform': Affine(1.0, 0.0, 0.0,
       0.0, 1.0, 0.0)}
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
VN609253_kelp.tif


/usr/local/lib/python3.10/dist-packages/rasterio/__init__.py:304: NotGeoreferencedWarning: Dataset has no geotransform, gcps, or rpcs. The identity matrix will be returned.
  dataset = DatasetReader(path, driver=driver, sharing=sharing, **kwargs)


Streaming output truncated to the last 5000 lines.
 [0 0 0 ... 0 0 0]]
CF296444_kelp.tif
(350, 350)
{'driver': 'GTiff', 'dtype': 'int8', 'nodata': None, 'width': 350, 'height': 350, 'count': 1, 'crs': None, 'transform': Affine(1.0, 0.0, 0.0,
       0.0, 1.0, 0.0)}
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
CF307324_kelp.tif
(350, 350)
{'driver': 'GTiff', 'dtype': 'int8', 'nodata': None, 'width': 350, 'height': 350, 'count': 1, 'crs': None, 'transform': Affine(1.0, 0.0, 0.0,
       0.0, 1.0, 0.0)}
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
CF432924_kelp.tif
(350, 350)
{'driver': 'GTiff', 'dtype': 'int8', 'nodata': None, 'width': 350, 'height': 350, 'count': 1, 'crs': None, 'transform': Affine(1.0, 0.0, 0.0,
       0.0, 1.0, 0.0)}
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0

In [54]:
import numpy as np

In [55]:
xx=  np.asarray(XX)
xx.shape

(8918, 350, 350)

In [56]:
yy = np.asarray(YY)

In [58]:
yy.shape

(8918,)

In [63]:
xx = xx.reshape(xx.shape[0],xx.shape[1],xx.shape[2],1)

In [64]:
xx.shape

(8918, 350, 350, 1)

In [65]:
yy = yy.reshape(yy.shape[0],1)

In [66]:
yy.shape

(8918, 1)

In [72]:
X = xx
y= yy

In [69]:
import keras

In [70]:
model = keras.models.Sequential()

initializers = {

}

model.add(
    keras.layers.Conv2D(
        24, 5, input_shape=(350,350,1),
        activation='relu',
    )
)
model.add( keras.layers.MaxPooling2D(2) )
model.add(
    keras.layers.Conv2D(
        48, 5, activation='relu',
    )
)
model.add( keras.layers.MaxPooling2D(2) )
model.add(
    keras.layers.Conv2D(
        96, 5, activation='relu',
    )
)
model.add( keras.layers.Flatten() )
model.add( keras.layers.Dropout(0.2) )

model.add( keras.layers.Dense(
    1, activation='softmax',
    )
)

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 346, 346, 24)      624       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 173, 173, 24)     0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 169, 169, 48)      28848     
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 84, 84, 48)       0         
 2D)                                                             
                                                                 
 conv2d_2 (Conv2D)           (None, 80, 80, 96)        115296    
                                                                 
 flatten (Flatten)           (None, 614400)            0

In [71]:
from sklearn.model_selection import train_test_split

In [73]:
 X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=33)

In [74]:
X_train.shape

(7134, 350, 350, 1)

In [75]:
y_train.shape

(7134, 1)

In [76]:
X_test.shape

(1784, 350, 350, 1)

In [77]:
y_test.shape

(1784, 1)

In [80]:
import tensorflow.keras.optimizers as optimizers

optimizer = optimizers.Adam(learning_rate=0.001)

In [81]:
model.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=['accuracy'])

In [83]:
# Fit the model
model.fit(X, y, validation_split=0.33, epochs=1, batch_size=100)

60/60 [==============================] - 404s 7s/step - loss: 147.9202 - accuracy: 0.9431 - val_loss: 4.6470 - val_accuracy: 0.0000e+00
