<a href="https://colab.research.google.com/github/BRIJNANDA1979/Segmenting-Kelp-Forests-/blob/main/Version_4_CNN_for_KELP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Next Step is CNN training with Train 5635 1 band  and rejected 469 7Band data.
469*7 = 3293  rejected  Label 0
5635 Trained   Label 1

Total in training:  8928

In [25]:
import pandas as pd
import os

In [26]:
train_kelp_path = '/content/drive/MyDrive/train_kelp'

In [27]:
train_kelp_files_list = os.listdir(train_kelp_path)

In [28]:
test_satellite_path = '/content/drive/MyDrive/test_satellite'

In [29]:
test_satellite_files_list = os.listdir(test_satellite_path)

In [30]:
Predicted = os.listdir('/content/drive/MyDrive/Predicted_all_bands_files')

In [31]:
len(Predicted)

6699

Rejected files  =   Test_satelleite - Predicted

469 7-Band files

In [40]:
for file in Predicted:
  s = file.split('_')
  ss = s[0] + '_satellite.tif'
  #print(ss)
  if ss in test_satellite_files_list:
    test_satellite_files_list.remove(ss)

In [33]:
len(test_satellite_files_list)

469

In [41]:
rejected_files_list = test_satellite_files_list

In [42]:
rejected_files_list[0:2]

['HP504630_satellite.tif', 'HR677407_satellite.tif']

In [43]:
rejected_list_with_7_bands = []
for i in rejected_files_list:
  for j in range(1,8):
    rejected_list_with_7_bands.append(i.split('.')[0]  + str(j) + '.tif')


In [44]:
rejected_list_with_7_bands[0:8]

['HP504630_satellite1.tif',
 'HP504630_satellite2.tif',
 'HP504630_satellite3.tif',
 'HP504630_satellite4.tif',
 'HP504630_satellite5.tif',
 'HP504630_satellite6.tif',
 'HP504630_satellite7.tif',
 'HR677407_satellite1.tif']

In [45]:
len(train_kelp_files_list)

5635

In [46]:
train_kelp_files_list[0:2]

['VN257517_kelp.tif', 'VN609253_kelp.tif']

In [47]:
X_list = train_kelp_files_list + rejected_list_with_7_bands

In [48]:
len(X_list)

8918

In [49]:
df = pd.DataFrame(X_list, columns=['file_name'])

In [50]:
df['file_name'][5633:5635]

5633    CW256294_kelp.tif
5634    CW399607_kelp.tif
Name: file_name, dtype: object

In [51]:
df['file_name'][5635:5640]

5635    HP504630_satellite1.tif
5636    HP504630_satellite2.tif
5637    HP504630_satellite3.tif
5638    HP504630_satellite4.tif
5639    HP504630_satellite5.tif
Name: file_name, dtype: object

In [52]:
label =[]
for i in range(0,5635):
  label.append(1)
for i in range(5635,8918):
  label.append(0)

In [53]:
df['label'] = label

In [54]:
df.head()

file_name  label
0  VN257517_kelp.tif      1
1  VN609253_kelp.tif      1
2  VN630519_kelp.tif      1
3  VN633188_kelp.tif      1
4  VN645015_kelp.tif      1

In [55]:
df.tail()

file_name  label
8913  HL852722_satellite3.tif      0
8914  HL852722_satellite4.tif      0
8915  HL852722_satellite5.tif      0
8916  HL852722_satellite6.tif      0
8917  HL852722_satellite7.tif      0

In [56]:
df['label'].value_counts()

1    5635
0    3283
Name: label, dtype: int64

In [57]:
pip install rasterio

In [58]:
s = 'GV801444_satellite2.tif'
s = s.split('_')


In [59]:
int(s[1][-5])

2

In [60]:
import rasterio

In [61]:
XX = []                        ### Read Raste data of each Band
YY = []
for i in df['file_name']:
  #print(i)
  if i in train_kelp_files_list:
    with rasterio.open('/content/drive/MyDrive/train_kelp/' + i) as src:
      print(src.shape)
      print(src.meta)
      print(src.read(1))
      data_array = src.read(1)    ##### _kelp is 1 Band only
      XX.append(data_array)
      YY.append(1)
  else:
    s = i.split('_')
    ss = s[0] + '_satellite.tif'
    band = int(s[1][-5])
    if band <=5:            ####  Exclude band 6 and 7 as these are cloud and DEM data
      with rasterio.open('/content/drive/MyDrive/test_satellite/' +ss) as src:
        data_array = src.read(band)     #### _satellite is 7 bands 1-7
        XX.append(data_array)
        YY.append(0)


/usr/local/lib/python3.10/dist-packages/rasterio/__init__.py:304: NotGeoreferencedWarning: Dataset has no geotransform, gcps, or rpcs. The identity matrix will be returned.
  dataset = DatasetReader(path, driver=driver, sharing=sharing, **kwargs)


Streaming output truncated to the last 5000 lines.
(350, 350)
{'driver': 'GTiff', 'dtype': 'int8', 'nodata': None, 'width': 350, 'height': 350, 'count': 1, 'crs': None, 'transform': Affine(1.0, 0.0, 0.0,
       0.0, 1.0, 0.0)}
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(350, 350)
{'driver': 'GTiff', 'dtype': 'int8', 'nodata': None, 'width': 350, 'height': 350, 'count': 1, 'crs': None, 'transform': Affine(1.0, 0.0, 0.0,
       0.0, 1.0, 0.0)}
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(350, 350)
{'driver': 'GTiff', 'dtype': 'int8', 'nodata': None, 'width': 350, 'height': 350, 'count': 1, 'crs': None, 'transform': Affine(1.0, 0.0, 0.0,
       0.0, 1.0, 0.0)}
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(350, 350)
{'driver': 'GTiff', 'dtype': 'int8', 'nodata': Non

In [62]:
import numpy as np

In [63]:
xx=  np.asarray(XX)
xx.shape

(7980, 350, 350)

In [64]:
yy = np.asarray(YY)

In [65]:
yy.shape

(7980,)

In [66]:
xx = xx.reshape(xx.shape[0],xx.shape[1],xx.shape[2],1)

In [67]:
xx.shape

(7980, 350, 350, 1)

In [68]:
yy = yy.reshape(yy.shape[0],1)

In [69]:
yy.shape

(7980, 1)

In [70]:
X = xx
y= yy

In [71]:
import keras

In [72]:
model = keras.models.Sequential()

initializers = {

}

model.add(
    keras.layers.Conv2D(
        24, 5, input_shape=(350,350,1),
        activation='relu',
    )
)
model.add( keras.layers.MaxPooling2D(2) )
model.add(
    keras.layers.Conv2D(
        48, 5, activation='relu',
    )
)
model.add( keras.layers.MaxPooling2D(2) )
model.add(
    keras.layers.Conv2D(
        96, 5, activation='relu',
    )
)
model.add( keras.layers.Flatten() )
model.add( keras.layers.Dropout(0.2) )

model.add( keras.layers.Dense(
    1, activation='sigmoid',
    )
)

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 346, 346, 24)      624       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 173, 173, 24)     0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 169, 169, 48)      28848     
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 84, 84, 48)       0         
 2D)                                                             
                                                                 
 conv2d_2 (Conv2D)           (None, 80, 80, 96)        115296    
                                                                 
 flatten (Flatten)           (None, 614400)            0

In [73]:
from sklearn.model_selection import train_test_split

In [74]:
 X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=33)

In [75]:
X_train.shape

(6384, 350, 350, 1)

In [76]:
y_train.shape

(6384, 1)

In [77]:
X_test.shape

(1596, 350, 350, 1)

In [78]:
y_test.shape

(1596, 1)

In [79]:
import tensorflow.keras.optimizers as optimizers

optimizer = optimizers.Adam(learning_rate=0.001)

In [80]:
model.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=['accuracy'])

In [81]:
# Fit the model
model.fit(X, y, validation_split=0.33, epochs=1, batch_size=100)

54/54 [==============================] - 360s 7s/step - loss: 0.0235 - accuracy: 0.9858 - val_loss: 195696464.0000 - val_accuracy: 0.1097


In [ ]:
#model.fit(X_train, y_train, validation_data=(X_test,y_test), epochs=1, batch_size=100)

72/72 [==============================] - 449s 6s/step - loss: 36.3731 - accuracy: 0.9372 - val_loss: 0.4164 - val_accuracy: 0.9563


In [82]:
prediction = model.predict(X_train)

200/200 [==============================] - 43s 215ms/step


In [83]:
y_train[5]



array([1])

Using CNN let us verify already Predicted using CVI....


In [84]:
Predicted_list_with_7_bands  = Predicted

In [85]:
len(Predicted_list_with_7_bands)

6699

In [86]:
Predicted_list_with_7_bands[0:10]

['VU293076_satellite2.tif',
 'VU293076_satellite3.tif',
 'VU293076_satellite4.tif',
 'VU293076_satellite5.tif',
 'VU293076_satellite6.tif',
 'VU293076_satellite7.tif',
 'WI130359_satellite1.tif',
 'WI130359_satellite2.tif',
 'WI130359_satellite3.tif',
 'WI130359_satellite4.tif']

In [87]:
PX = []
XP = []    ### Predicted data
YP = []
for i in Predicted_list_with_7_bands:
  PX.append(i)
for i in PX:
  #print(i)
  s = i.split('_')
  ss = s[0] + '_satellite.tif'
  band = int(s[1][-5])
  if(band<=5):
    with rasterio.open('/content/drive/MyDrive/test_satellite/' +ss) as src:
      data_array = src.read(band)     #### _satellite is 5 out of 7 bands 1-5
      XP.append(data_array)
      YP.append(1)


/usr/local/lib/python3.10/dist-packages/rasterio/__init__.py:304: NotGeoreferencedWarning: Dataset has no geotransform, gcps, or rpcs. The identity matrix will be returned.
  dataset = DatasetReader(path, driver=driver, sharing=sharing, **kwargs)


In [88]:
XP = np.asarray(XP)

In [94]:
XP.shape            ####  4785 out of 6699 by excluding bands 6 and 7 as theses are cloud and DEM

(4785, 350, 350, 1)

In [95]:
XP = XP.reshape(XP.shape[0],XP.shape[1],XP.shape[2],1)

In [96]:
XP.shape

(4785, 350, 350, 1)

In [97]:
YP = np.asarray(YP)

In [98]:
YP = YP.reshape(YP.shape[0],1)

In [99]:
YP.shape

(4785, 1)

In [100]:
Prediction_by_CNN = model.predict(XP)


150/150 [==============================] - 32s 213ms/step


In [101]:
len(Prediction_by_CNN)

4785

In [102]:
Prediction_by_CNN[0:10]

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]], dtype=float32)

In [108]:
Predicted_list_with_5_bands = Prediction_by_CNN

In [109]:
count=0
for i in Prediction_by_CNN:
  if i[0] < 0.5 :
    count = count + 1
print(count)

0


In [110]:
Predicted_list_with_5_bands[0:10]               ##########3   GC205345_satellite1.tif

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]], dtype=float32)

In [112]:
loc =0
for file in Predicted_list_with_5_bands:
  if(file == 'GC205345_satellite1.tif'):
    print(file)
    print(loc)
    print(Prediction_by_CNN[loc])
    break

  loc = loc + 1

<ipython-input-112-62642b3b96f8>:3: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if(file == 'GC205345_satellite1.tif'):


In [113]:
loc =0                                            ###########3 AC799254_satellite.tif
for file in Predicted_list_with_7_bands:
  if(file == 'AC799254_satellite.tif'):
    print(file)
    print(loc)
    break
  loc = loc + 1

TI176604_satellite6.tif   unexpected file   Still not detected by new CNN